#participants_tsv: 'config/participants.tsv' #7T subjects used in basalfb study

#test list with 5 subjects
participants_tsv: 'config/participants.tsv'

#singularity containers:
#singularity:
#  neuroglia: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
#  freesurfer: /project/6050199/akhanf/singularity/bids-apps/khanlab_freesurfer_v6.0.1-subfields.img
#  connectome_workbench: /project/6050199/akhanf/singularity/bids-apps/khanlab_connectome-workbench_latest.sif
#  fsl_cuda: /project/6050199/akhanf/singularity/bids-apps/fsl_6.0.3_cuda9.1.sif
singularity:
  connectome_workbench: /path/to/workbench.sif
  pythondeps: /path/to/pythondeps.sif
  fsl: /path/to/fsl.sif
  neuroglia: ""
  freesurfer: ""
  connectome_workbench: ""
  fsl_cuda: ""


#path to your freesurfer license file:
fs_license: /usr/local/freesurfer/8.1.0/license.txt



#set-up paths to inputs here:


#path to subject freesurfer dir (containing surf/ and mri/ subfolders) 
# use the {subject} wildcard here.. 
in_freesurfer: 'freesurfer/sub-{subject}'
in_freesurfer_root: 'freesurfer'
in_freesurfer_tar: /project/6050199/ext-data/hcp1200/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/{subject}.freesurfer.tar



template_binary_mask:
  fullBF: /home/m-ehara/project/PNI/resource/seed_1p6mm.nii.gz

prob_seg_threshold: 0.5

template: MNI152NLin6Asym
ants_invwarp_nii: /home/m-ehara/project/PNI/derivatives/sub-{subject}/ses-01/xfm/sub-{subject}_ses-01_from-nativepro_brain_to-MNI152_2mm_mode-image_desc-SyN_1InverseWarp.nii.gz
ants_warp_nii: /home/m-ehara/project/PNI/derivatives/sub-{subject}/ses-01/xfm/sub-{subject}_ses-01_from-nativepro_brain_to-MNI152_0.8mm_mode-image_desc-SyN_1Warp.nii.gz
ants_ref_nii: /usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz
#list of ROIs in target segmentations 
targets_dseg_tsv: resources/label-hcpmmp180_dseg.tsv
targets_atlas_name: 'schaefer-400'

# bedpost
fsl_bedpost_dir: /home/m-ehara/project/PNI/derivatives/sub-{subject}/ses-01/dwi
bedpost_mean_s0_samples: 'sub-{subject}_ses-01_space-dwi_desc-brain_mask.nii.gz'
bedpost_merged_prefix: 'sub-{subject}_ses-01_space-dwi_desc-preproc_dwi'

#maximum number of clusters in spectral clustering
# will perform with k=range(2,max_k+1)
max_k: 8


#tractography parameters
probtrack:
    seed_resolution: 1.6
    res_name: dwi # bids deriv filename will have res-{res_name}

    nsamples: 10000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 


probtrack_tractmap:
    seed_resolution: 0.5
    res_name: super #bids deriv filename will have res-{res_name}
    nsamples: 1000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --randfib=2' 
